export const siteConfig = {
  name: "Versa Growth Ventures",
  tagline: "Diversified Growth. Powered by AI.",
  description: "A multi-venture enterprise spanning education, technology, trading, exports, digital marketing, and AI innovation.",
  location: "Kerala, India",
  phone: "+91 8891129111",
  whatsapp: "918891129111",
  email: "info@versagrowthventures.com",
  address: "Kochi, Kerala, India",
}

export const ventures = [
  {
    id: "ipb",
    name: "IPB Kochi",
    tagline: "Kerala's Premier Banking Institute",
    description: "13,200+ students placed in leading banks across India. ISO certified. NSDC approved.",
    icon: "GraduationCap",
    color: "#C9A84C",
    stat: "13,200+ Placements",
    url: "https://ipb.versagrowthventures.com",
    size: "large" as const,
    comingSoon: false,
  },
  {
    id: "digital",
    name: "Versa Digital",
    tagline: "AI-Powered Digital Marketing",
    description: "Marketing that thinks for itself. AI-driven SEO, social media, and performance marketing.",
    icon: "TrendingUp",
    color: "#00D4FF",
    stat: "3x Average ROI",
    url: "https://digital.versagrowthventures.com",
    size: "medium" as const,
    comingSoon: false,
  },
  {
    id: "global",
    name: "Versa Global",
    tagline: "Study Abroad Consultancy",
    description: "Your dream university in 60+ countries. Expert guidance for overseas education.",
    icon: "Globe",
    color: "#4A7C59",
    stat: "60+ Countries",
    url: "https://global.versagrowthventures.com",
    size: "medium" as const,
    comingSoon: false,
  },
  {
    id: "elyra",
    name: "Elyra AI",
    tagline: "AI Employees for Business",
    description: "AI agents that work 24/7 — lead nurturing, sales, recruitment, and customer support.",
    icon: "Brain",
    color: "#6E44FF",
    stat: "100% AI Powered",
    url: "https://elyra.versagrowthventures.com",
    size: "small" as const,
    comingSoon: false,
  },
  {
    id: "trading",
    name: "Versa Trading",
    tagline: "Smart Market Intelligence",
    description: "AI-powered trading insights and market analysis for modern investors.",
    icon: "BarChart2",
    color: "#8FBC5A",
    stat: "Coming Soon",
    url: "#",
    size: "small" as const,
    comingSoon: true,
  },
  {
    id: "exports",
    name: "Versa Exports",
    tagline: "Global Trade Solutions",
    description: "Connecting Kerala businesses to global markets with seamless export services.",
    icon: "Package",
    color: "#C9A84C",
    stat: "Coming Soon",
    url: "#",
    size: "small" as const,
    comingSoon: true,
  },
]

export const metrics = [
  { label: "Ventures", value: 6, suffix: "" },
  { label: "Placements", value: 13200, suffix: "+" },
  { label: "Countries", value: 60, suffix: "+" },
  { label: "AI Powered", value: 100, suffix: "%" },
]

export const contactInfo = {
  phone: "+91 8891129111",
  email: "info@versagrowthventures.com",
  address: "Kochi, Kerala, India",
  whatsapp: "918891129111",
}
